### ISSUE TITLE
Emoj does not show

### ISSUE THREAD

**Issue by spencerimp** [rhysd/Shiba#34]
Hi Shiba developers,

Just a report that some of the emoj are not rendered in Shiba on my macOX Sierra

1. :checkered_flag:
2. :white_check_mark:
3. :green_heart:
4. :arrow_up:
5. :arrow_down:

The screenshot is attached as follows
![shiba](https://cloud.githubusercontent.com/assets/3917087/20525594/7a475c10-b0c0-11e6-9bf0-9f63abb2f680.png)

**Comment by rhysd** [comment]
Nice catch! Emojis had been added before Sierra was public. I need to update them.

**Comment by rhysd** [comment]
I found that [marked](https://github.com/chjj/marked) parses `:foo_bar:` into two piecies; the text `:foo` and the bold text `_bar:`. So this is originally the issue of marked. But marked will not implement emoji because it's not a markdown standard stuff. We need to handle parsing emojis by our side.

**Comment by rhysd** [comment]
I fixed in above commit. 1.0.4 will be released after I confirmed behavior on Linux and Windows (my dev environment is OS X).

![2016-11-29 15 42 03](https://cloud.githubusercontent.com/assets/823277/20699588/713e751e-b64b-11e6-8015-21d2959af4e0.png)
